name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 9999

    steps:
    - name: Setup files
      env: 
        SSHD_PORT: ${{ secrets.SSHD_PORT }}
        SSHD_USER: ${{ secrets.SSHD_USER }}
        SSHD_PASS: ${{ secrets.SSHD_PASS }}
        SSHD_KEY: ${{ secrets.SSHD_KEY }}
        TGT_AUTH: ${{ secrets.TGT_AUTH }}
        TGT_URL: ${{ secrets.TGT_URL }}
      run: |
        sudo apt update && sudo apt install uuid
        sudo mkdir -p /var/run/sshd
        echo "PasswordAuthentication yes" | sudo tee -a /etc/ssh/sshd_config
        echo "TCPKeepAlive yes" | sudo tee -a /etc/ssh/sshd_config
        sudo adduser $SSHD_USER --gecos "First Last,RoomNumber,WorkPhone,HomePhone" --disabled-password
        sudo usermod -aG sudo $SSHD_USER
        echo "$SSHD_USER:$SSHD_PASS" | sudo chpasswd
        echo "$SSHD_USER ALL=(ALL) NOPASSWD:ALL" | sudo EDITOR="tee -a" visudo
        sudo mkdir "/home/${SSHD_USER}/.ssh" && sudo chmod 755 "/home/${SSHD_USER}/.ssh"
        echo $SSHD_KEY | sudo tee "/home/${SSHD_USER}/.ssh/authorized_keys" && sudo chmod 600 "/home/${SSHD_USER}/.ssh/authorized_keys" && sudo chown $SSHD_USER:$SSHD_USER -R "/home/${SSHD_USER}/.ssh"
        sudo service ssh restart
        echo -e "IyEvYmluL2Jhc2gKCmJ1ZmZlcj0iIgoKY2xvdWRmbGFyZWQgdHVubmVsIC0tdXJsIHNzaDovL2xvY2FsaG9zdDoyMiAyPiA+KAogICAgewogICAgICAgIHN0YXJ0PSQoZGF0ZSArJXMpCgogICAgICAgIHdoaWxlIElGUz0gcmVhZCAtciBsaW5lOyBkbwogICAgICAgICAgICBidWZmZXIrPSIkbGluZSIkJ1xuJwogICAgICAgICAgICAoKCAkKGRhdGUgKyVzKSAtIHN0YXJ0ID49IDYgKSkgJiYgYnJlYWsKICAgICAgICBkb25lCgogICAgICAgIGN1cmwgLVggUFVUIFwKICAgICAgICAgICAgLUggIkF1dGhvcml6YXRpb246IEJhc2ljIF9BVVRIIiBcCiAgICAgICAgICAgIC0tZGF0YS1iaW5hcnkgIiRidWZmZXIiIFwKICAgICAgICAgICAgIl9VUkwvJCh1dWlkZ2VuKSIKICAgIH0gJgopIHx8IGV4aXQgMA==" | base64 -d | sudo tee "/home/${SSHD_USER}/run.sh" && sudo chmod +x "/home/${SSHD_USER}/run.sh" && sudo chown "${SSHD_USER}:${SSHD_USER}" "/home/${SSHD_USER}/run.sh"
        sudo sed -i 's/_AUTH/'"$TGT_AUTH"'/' "/home/${SSHD_USER}/run.sh"
        sudo sed -i 's/_URL/'"$TGT_URL"'/' "/home/${SSHD_USER}/run.sh"
        curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | grep -m 1 -wo "https.*cloudflared-linux.*amd64" | xargs curl -o cloudflared -L && chmod +x cloudflared && sudo mv cloudflared /usr/bin
        sudo -u $SSHD_USER /home/$SSHD_USER/run.sh || exit 0
